### ISSUE TITLE
I don't get any styling

### ISSUE THREAD

**Issue by 4044ever** [FileFabrik/hugo-tailwindcss-jit#1]
I don't get any CSS styling. Neither in 1313, nor in Live Server on /public/.

The minified CSS in `/public/css/` does not look correct to me: `@tailwind base;@tailwind components;@tailwind utilities`

In `head.html ` the link is asking for` css/tailwind.css` - there isn't such file.

Or maybe I got something wrong. Would be really nice if this could work.

**Comment by Filefabrik** [comment]
Please tell me the Version of your Hugo and your Tailwind.

This "Demo-Project" was made for/with

node.js: lts/fermium -> v14.17.0
hugo: hugo v0.83.1
and
"tailwindcss": "^2.1.2"

**Comment by 4044ever** [comment]
Well, latest....
node -v  v14.18.0
hugo v0.88.1 (ext.)
tailwindcss: "^2.2.17"

The Tailwind I could change though.

**Comment by Filefabrik** [comment]
I have tested the Demo again and updated to latest versions including update 
hugo to: hugo_extended_0.88.1_Linux-64bit.deb

```json
{
  "name": "hugo-tailwindcss-jit",
  "version": "1.0.0",
  "description": "Get Static Side Generator Hugo running with tailwindcss 2 and JIT",
  "main": "index.js",
  "license": "MIT",
  "author": "FileFabrik <rt@FileFabrik.com>",
  "scripts": {
    "devWatcherTailwindStartFirst": "TAILWIND_MODE=watch NODE_ENV=development postcss ./assets/css/main.css -c ./assets/css/tailwind.config.js -o ./assets/css/tailwind.css -w",
    "server": "hugo server  --disableFastRender",
    "buildTailwindDistCssOnly": "TAILWIND_MODE=build NODE_ENV=production postcss ./assets/css/main.css -o ./assets/css/tailwind.css",
    "buildTailwindAndHugo": "TAILWIND_MODE=build NODE_ENV=production postcss ./assets/css/main.css -o ./assets/css/tailwind.css && hugo --gc --minify"
  },
  "dependencies": {
    "autoprefixer": "^10.3.7",
    "npm": "^7.14.0",
    "postcss": "^8.3.9",
    "postcss-cli": "^8.3.1",
    "tailwindcss": "^2.2.17"
  },
  "devDependencies": {
    "postcss-import": "^14.0.2"
  }
}```

it works as expected...
